# dcc-admin-ui Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: dcc-admin-ui
    app: aml
    version: "6.5.1"
  name: dcc-admin-ui
  namespace: redpoint-mercury
spec:
  selector:
    matchLabels:
      role: dcc-admin-ui
      app: aml
      version: "6.5.1"
  replicas: 1
  template:
    metadata:
      labels:
        role: dcc-admin-ui
        app: aml
        version: "6.5.1"
    spec:
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      containers:
      - name: dcc-admin-ui
        image: docker.io/redpointglobal/dcc_admin_ui:v6.5.1
        imagePullPolicy: Always
        ports:
        - name: dcc-admin-ui
          containerPort: 8990
        env: 
          - name: DCC_API_NAME
            value: dcc-servicesapi
          - name: DCC_API_PORT
            value: "8900"
          - name: DCC_API_PROTO
            value: http
          - name: ML_API_NAME
            value: ml-servicesapi
          - name: ML_API_PORT
            value: "8910"
          - name: ML_API_PROTO
            value: http
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8990
          periodSeconds: 20
          timeoutSeconds: 15
          failureThreshold: 3
      initContainers:
      - name: init-dcc-servicesapi
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup dcc-servicesapi; do echo waiting for dcc-servicesapi; sleep 2; done;']
        
