global:
  namespace: redpoint-aml #redpoint-aml
  cloudProvider: azure # or google or amazon 
  ingress:
    subnet_name: snet-rgoc-nonprod-eus2-aks # Replace with your virtual network subnet if cloudprovider is azure
    internal: true
  replicaCount: 1
  auth_services: keycloak # or keycloak or mdm

application:
  name: redpoint-aml
  environment: dev
  region: eastus2

images:
  repository: redpointglobal
  tag: v6.5.2
  pullSecret: docker-io

mongodb:
  enabled: false
  connection_string: mongodb+srv://<username>:<password>@<mongo server address>/?retryWrites=true&w=majority
  aml_db_name: redpoint-aml

keycloak:
  keycloak_user: sso-admin@noemail.com
  keycloak_password: 7rU8w9o8ocTa8Zp1
  postgresql:
    enabled: false
    db_address: postgresql
    db_name: deletemetest
    db_user: keycloak
    db_password: 7rU8w9o8ocTa8Zp1

nginx:
  enabled: true

replicas: 1

envs:
  RPI_ENABLED: false 
  RPI_CACHES_ENABLED: true
  RPI_NAME: rpi.example.com             # FQDN on your RPI server (Optional - Only required for RPI integration) 
  RPDM_HOST: rpdm.example.com           # FQDN on your RPDM server (Optional - Only required for RPDM integration) 
  RPDM_PORT: 20420
  RPDM_USER: rpdm.svs                   # RPDM username
  RPDM_PASS: "example-password" 
  DATASET_CSV_STORAGE: ADL2
  DATASET_CSV_DIR: /example
  ADL2_ACCOUNT_NAME: example               
  SITE_URL: 
  RPI_READ_TIMEOUT: 300000
  SSO_ENABLED: true
  MSGQ_TRAINER_CHANNEL: training_tasks
  TRAINING_HEALTHY_MINS: 1500
  SMTP_HOST: smtp.example.com
  SMTP_USER: example_smtp_user
  SMTP_PORT: 587
  SMTP_PASS: superStrongExamplep@sswd

ingress:
  host: redpoint-aml.example.com

securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault




