global:
  application:
    name: redpoint-mercury
    version: "6.6.0"
    environment: prod 
  # Define the Kubernetes namespace in which the services will be deployed.
  # This namespace should already exist or be created prior to deployment.
  namespace: redpoint-mercury

  # Set the number of replicas for the deployment.
  # This determines how many instances of each pod will be created.
  replicaCount: 1

  # Specify the image tag for the main application.
  # This tag refers to a specific version of the docker image to be deployed.
  image_tag: v6.6.0

  # Select the cloud provider where the infrastructure is hosted.
  # Options include 'azure', 'google', or 'amazon'.
  # This setting may influence certain cloud-specific configurations.
  cloudProvider: azure
  deploymentType: client
  # Define the deployment type.
  # 'client' is for external clients, while 'internal' is reserved for Redpoint users.
  # This may affect access controls and available features.
  imagePullPolicy: Always
  images:
    repository: redpointglobal
    tag: v6.6.0
    pullSecret: docker-io

databases:
  # MongoDB Configuration
  mongodb:
    # Provide the MongoDB connection string.
    # Replace <username>, <password>, and <mongodb server fqdn> with your MongoDB credentials and server details.
    # This string is used to establish a connection to your MongoDB database.
    connection_string: mongodb+srv://<username>:<password>@<mongodb server fqdn>/?retryWrites=true

  # Keycloak Database Configuration
  keycloak:
    # Specify the Keycloak admin user's email.
    # This email is used for administrative access to the Keycloak instance.
    keycloak_user: sso-admin@noemail.com

    # Define the address of the PostgreSQL server used by Keycloak.
    # This should be the fully qualified domain name (FQDN) of your PostgreSQL server.
    db_address: postgresql.example.com

    # Name of the Keycloak database in PostgreSQL.
    # This is the specific database where Keycloak stores its data.
    db_name: redpointmercury

    # Set the username for accessing the Keycloak database.
    # This user should have the necessary permissions on the Keycloak database.
    db_user: redpointmercury

    # Provide the password for the Keycloak database user.
    # Ensure this password is kept secure and known only to authorized personnel.
    db_password: example-password


envs:
  # Default Admin User for Mercury
  # This is the username for the default administrative account.
  # Note: It is recommended to change this from the default for security purposes.
  DEFAULT_DCC_ADMIN_USER: admin@redpointmercury.com

  # Default Admin Password for Mercury
  # This is the password for the default administrative account.
  # Note: It is crucial to change this default password to maintain system security.
  DEFAULT_DCC_ADMIN_PASS: .RedPoint123
  # Enable or disable the RPI service.
  # Set to 'true' to enable or 'false' to disable.
  RPI_ENABLED: false 

  # Enable or disable caching mechanisms in RPI.
  # Caching can improve performance in data-intensive operations.
  RPI_CACHES_ENABLED: true

  # Define the Fully Qualified Domain Name (FQDN) of your RPI server.
  # This is optional and only required if you are integrating with RPI.
  RPI_NAME: rpi.example.com

  # Specify the FQDN of your RPDM server.
  # This is optional and only needed for integrating with RPDM.
  RPDM_HOST: rpdm.example.com

  # Set the port number for the RPDM server connection.
  RPDM_PORT: 20420

  # Enter the username for the RPDM service.
  RPDM_USER: rpdm.svs

  # Provide the password for the RPDM user.
  # Ensure this password is stored securely.
  RPDM_PASS: "example-password"

  # Specify the storage type for dataset CSV files.
  # Example: Azure Data Lake Storage Gen2 (ADL2)
  DATASET_CSV_STORAGE: ADL2

  # Define the directory path for storing dataset CSV files.
  DATASET_CSV_DIR: /example

  # Set the account name for the Azure Data Lake Storage Gen2 service.
  ADL2_ACCOUNT_NAME: redpointmercury

  # Set the read timeout for RPI in milliseconds.
  # This value determines how long the system waits before timing out a read operation.
  RPI_READ_TIMEOUT: 300000

  # Enable or disable Single Sign-On (SSO) functionality.
  # Set to 'true' to enable SSO.
  SSO_ENABLED: true

  # Define the message queue channel for training tasks.
  # This channel is used for queuing and processing training-related tasks.
  MSGQ_TRAINER_CHANNEL: training_tasks

  # Specify the duration (in minutes) to consider the training service as healthy.
  TRAINING_HEALTHY_MINS: 1500

  # Enter the host address for the SMTP server.
  # This is used for email sending functionalities.
  SMTP_HOST: smtp.example.com

  # Provide the username for the SMTP server.
  SMTP_USER: example-smtp-user

  # Set the port number for the SMTP server.
  SMTP_PORT: 587

  # Enter the password for the SMTP server.
  # Ensure this password is stored securely.
  SMTP_PASS: example-smtp-password


ingress:
  domain: rdpnt.com
  host: redpointmercury

securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault