global:
  application:
    name: redpoint-mercury
    version: "6.6.0"
    environment: prod 
  # Define the Kubernetes namespace in which the services will be deployed.
  # This namespace should already exist or be created prior to deployment.
  namespace: redpoint-mercury

  # Set the number of replicas for the deployment.
  # This determines how many instances of each pod will be created.
  replicaCount: 1

  # Specify the image tag for the main application.
  # This tag refers to a specific version of the docker image to be deployed.
  image_tag: v6.6.0

  # Select the cloud provider where the infrastructure is hosted.
  # Options include 'azure', 'google', or 'amazon'.
  # This setting may influence certain cloud-specific configurations.
  cloudProvider: azure
  deploymentType: client
  # Define the deployment type.
  # 'client' is for external clients, while 'internal' is reserved for Redpoint users.
  # This may affect access controls and available features.
  imagePullPolicy: Always
  images:
    repository: redpointglobal
    tag: v6.6.0
    pullSecret: docker-io

databases:
  # MongoDB Configuration
  mongodb:
    # Provide the MongoDB connection string.
    # Replace <username>, <password>, and <mongodb server fqdn> with your MongoDB credentials and server details.
    # This string is used to establish a connection to your MongoDB database.
    connection_string: mongodb+srv://<username>:<password>@<mongodb server fqdn>/?retryWrites=true

  # Keycloak Database Configuration
  keycloak:
    # Specify the Keycloak admin user's email.
    # This email is used for administrative access to the Keycloak instance.
    keycloak_user: sso-admin@noemail.com

    # Define the address of the PostgreSQL server used by Keycloak.
    # This should be the fully qualified domain name (FQDN) of your PostgreSQL server.
    db_address: postgresql.example.com

    # Name of the Keycloak database in PostgreSQL.
    # This is the specific database where Keycloak stores its data.
    db_name: redpointmercury

    # Set the username for accessing the Keycloak database.
    # This user should have the necessary permissions on the Keycloak database.
    db_user: redpointmercury

    # Provide the password for the Keycloak database user.
    # Ensure this password is kept secure and known only to authorized personnel.
    db_password: example-password


envs:
  RPI_ENABLED: false 
  RPI_CACHES_ENABLED: true
  RPI_NAME: rpi.example.com             # FQDN on your RPI server (Optional - Only required for RPI integration) 
  RPDM_HOST: rpdm.example.com           # FQDN on your RPDM server (Optional - Only required for RPDM integration) 
  RPDM_PORT: 20420
  RPDM_USER: rpdm.svs                   # RPDM username
  RPDM_PASS: "example-password" 
  DATASET_CSV_STORAGE: ADL2
  DATASET_CSV_DIR: /example
  ADL2_ACCOUNT_NAME: example               
  SITE_URL: 
  RPI_READ_TIMEOUT: 300000
  SSO_ENABLED: true
  MSGQ_TRAINER_CHANNEL: training_tasks
  TRAINING_HEALTHY_MINS: 1500
  SMTP_HOST: 
  SMTP_USER: 
  SMTP_PORT: 587
  SMTP_PASS: 

ingress:
  domain: rdpnt.com
  host: redpointmercury

securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault