global:
  namespace: redpoint-mercury
  cloudProvider: azure 
  ingress:
    subnet_name: snet-aks-workload 
    internal: true
  replicaCount: 0
  auth_services: keycloak 

application:
  name: redpoint-mercury
  environment: dev
  region: eastus2

images:
  repository: redpointglobal
  tag: v6.6.0
  pullSecret: docker-io

keycloak:
  keycloak_user: sso-admin@noemail.com
  postgresql:
    enabled: false
    db_address: postgres
    db_name: redpointmercury
    db_user: redpointmercury

replicas: 1

envs:
  RPI_ENABLED: false 
  RPI_CACHES_ENABLED: true
  RPI_NAME: rpi.example.com             # FQDN on your RPI server (Optional - Only required for RPI integration) 
  RPDM_HOST: rpdm.example.com           # FQDN on your RPDM server (Optional - Only required for RPDM integration) 
  RPDM_PORT: 20420
  RPDM_USER: rpdm.svs                   # RPDM username
  RPDM_PASS: "example-password" 
  DATASET_CSV_STORAGE: ADL2
  DATASET_CSV_DIR: /example
  ADL2_ACCOUNT_NAME: example               
  SITE_URL: 
  RPI_READ_TIMEOUT: 300000
  SSO_ENABLED: true
  MSGQ_TRAINER_CHANNEL: training_tasks
  TRAINING_HEALTHY_MINS: 1500
  SMTP_HOST: email-smtp.us-east-1.amazonaws.com
  SMTP_USER: AKIA4YLE5WJY2L7F5COO
  SMTP_PORT: 587
  SMTP_PASS: BOEXaMouJWEO9NcsZRZpIHuNPZkqbV33eUo7yNCUYKRm

ingress:
  host: dev-mercury-dockerh.rg1cloud.com

securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault