# dcc-socketio deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: dcc-socketio
    app: aml
    version: 6.5.1
  name: dcc-socketio
  namespace: {{ .Values.application.namespace }}
spec:
  selector:
    matchLabels:
      role: dcc-socketio
      app: aml
      version: 6.5.1
  replicas: 1
  template:
    metadata:
      labels:
        role: dcc-socketio
        app: aml
        version: 6.5.1
    spec:
      imagePullSecrets:
      - name: docker-io
      containers:
      - name: dcc-socketio
        image: redpointglobal/dcc_socketio:{{ .Values.images.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8930
        env: 
        - name: SOCKETIO_HOST
          value: "0.0.0.0"
        - name: SOCKETIO_PORT
          value: "8930"
        resources: {}
      restartPolicy: Always
