apiVersion: v1
kind: Service
metadata:
  name: messageq
  namespace: {{ .Values.global.namespace }}
  labels:
    role: messageq
spec:
  ports:
  - port: 5672
    protocol: TCP
  selector:
    role: messageq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: messageq
    app: aml
  name: messageq
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      role: messageq
      app: aml
  replicas: {{  .Values.replicas }}
  template:
    metadata:
      labels:
        role: messageq
        app: aml 
    spec:
      containers:
      - name: messageq
        image: rabbitmq:3.6.10-management
        ports:
        - name: messageq
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_VHOST
          value: /
        - name: RABBITMQ_ERLANG_COOKIE
          value: "1234"
      restartPolicy: Always
      nodeSelector:
        pool: rpengshared
      tolerations:
        - effect: NoSchedule
          key: pool
          operator: Equal
          value: rpengshared