apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: {{ .Values.global.namespace }}
  labels:
    role: cache
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    role: cache
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: cache
    app: aml
    version: {{  .Values.images.tag }}
  name: cache
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      role: cache
      app: aml
      version: {{  .Values.images.tag }}
  replicas: {{  .Values.replicas }}
  template:
    metadata:
      labels:
        role: cache
        app: aml
        version: {{  .Values.images.tag }}
    spec:
      containers:
      - name: cache
        image: redis:3.2.8-alpine
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
      nodeSelector:
        pool: rpengshared
      tolerations:
        - effect: NoSchedule
          key: pool
          operator: Equal
          value: rpengshared