# keycloak Deployment
{{- if eq .Values.global.auth_services "keycloak" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: keycloak
    app: aml
  name: keycloak
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      role: keycloak
      app: aml
  replicas: 1
  template:
    metadata:
      labels:
        role: keycloak
        app: aml
    spec:
      imagePullSecrets:
      - name: docker-io
      containers:
      - name: keycloak
        image: redpointglobal/keycloak:{{ .Values.images.tag }}
        imagePullPolicy: Always
        ports:
        - name: http 
          containerPort: 8080
        - name: https
          containerPort: 8443
        env: 
        - name: KEYCLOAK_PRODUCTION
          value: "false"
        - name: KEYCLOAK_ADMIN_USER
          value: "sso-admin@noemail.com"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: yKo3BN671b0m
#          valueFrom:
#            secretKeyRef:
#              name: keycloak
#              key: KEYCLOAK_PASSWORD
        - name: KEYCLOAK_DATABASE_PASSWORD
          value: yKo3BN671b0m
#          valueFrom:
#            secretKeyRef:
#              name: postgresql
#              key: POSTGRESQL_PASSWORD
        - name: KEYCLOAK_DATABASE_HOST
          value: {{ .Values.keycloak.postgresql.db_address | quote }}
        - name: KEYCLOAK_DATABASE_NAME
          value: {{ .Values.keycloak.postgresql.db_name | quote }}
        - name: KEYCLOAK_DATABASE_PORT
          value: "5432"
        - name: KEYCLOAK_DATABASE_USER
          value: {{ .Values.keycloak.postgresql.db_user }}
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
      restartPolicy: Always
      nodeSelector:
        pool: rpengshared
      tolerations:
        - effect: NoSchedule
          key: pool
          operator: Equal
          value: rpengshared
          
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace }}
  labels:
    role: keycloak
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
    protocol: TCP
  - port: 8443
    name: https
    targetPort: 8443
    protocol: TCP
  selector:
    role: keycloak
{{- end }}