# auth-services Deployment
{{- if eq .Values.global.auth_services "mdm" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: auth-services
    app: aml
  name: auth-services
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      role: auth-services
      app: aml
  replicas: {{  .Values.replicas }}
  template:
    metadata:
      labels:
        role: auth-services
        app: aml
    spec:
      imagePullSecrets:
      - name: docker-io
      containers:
      - name: auth-services
        image: redpointglobal/auth_services_dev:v6.6.0-SNAPSHOT
        imagePullPolicy: Always
        ports: 
        - containerPort: 9090
        - containerPort: 9901
        - containerPort: 9903
        - containerPort: 9908
        env: 
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mongo-conn-string
              key: MONGODB_NAME
        resources: {}
      restartPolicy: Always
{{- end }}