# ml-servicesapi Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: ml-servicesapi
    app: aml
    version: 6.5.1
  name: ml-servicesapi
  namespace: {{ .Values.application.namespace }}
spec:
  selector:
    matchLabels:
      role: ml-servicesapi
      app: aml
      version: 6.5.1
  replicas: 1
  template:
    metadata:
      labels:
        role: ml-servicesapi
        app: aml
        version: 6.5.1
    spec:
      imagePullSecrets:
      - name: docker-io
      containers:
      - name: ml-servicesapi
        image: redpointglobal/ml_servicesapi:{{ .Values.images.tag }}
        imagePullPolicy: Always
        ports:
        - name: ml-servicesapi
          containerPort: 8910
        env:
        - name: CACHE_CHANNEL
          value: cache_updates
        - name: CACHE_NAME
          value: cache
        - name: CACHE_PORT
          value: "6379"
        - name: JAVA_OPTS
          value: -Xmx1g
        - name: MONGODB_ML_DB
          value: redpoint_dcc_shared
        - name: MONGODB_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-conn-string
              key: MONGODB_NAME
        - name: MONGODB_TYPE
          value: MONGO 
        - name: PREDICT_ENABLED
          value: "true"
        - name: PREDICT_NAME
          value: predictor
        - name: PREDICT_PORT
          value: "11000"
        - name: RABBITMQ_ENABLED
          value: "true"
        - name: RABBITMQ_ML_Q
          value: training_tasks
        - name: RABBITMQ_NAME
          value: messageq
        - name: REST_HTTPS_PORT
          value: "8913"
        - name: REST_HTTP_PORT
          value: "8910"
        - name: REST_NAME
          value: 0.0.0.0
        - name: TRAINING_ENABLED
          value: "true"
        - name: TRAINING_NAME
          value: trainer
        - name: TRAINING_PORT
          value: "11001"
        - name: IS_DBAPI
          value: "false"
        - name: RPDM_ENABLED            # Enable RPDM for data connections
          value: "false"
        - name: RPDM_HOST               # Hostname or IP for RPDM server
          value: ""
        - name: RPDM_USER               # Username for RPDM server
          value: ""
        - name: RPDM_TEMP_DIR           # Temporary directory on RPDM server
          value: ""
        - name: RPDM_ML_URI             # URI for ML-ServicesAPI accessible by RPDM server
          value: ""
        - name: DATASET_CSV_STORAGE     # Dataset storage type [ADL2|GCS|S3]
          value: ""
        - name: DATASET_CSV_DIR         # Directory for storing datasets
          value: ""
        - name: ADL2_ACCOUNT_NAME       # Account name for Azure Data Lake 2
          value: ""
        - name: S3_ACCESS_KEY           # Access key for Amazon S3 Buckets
          value: ""
        - name: GCS_PROJECT_ID          # Project id for Google Cloud Storage
          value: ""
        - name: KEYCLOAK_HOST
          value: "keycloak"
        - name: KEYCLOAK_USER
          value: "admin"
        livenessProbe:
          httpGet:
            path: /api-ml/v2/healthcheck
            port: 8910
          periodSeconds: 20
          timeoutSeconds: 15
          failureThreshold: 3
      initContainers:
      - name: init-messageq
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup messageq; do echo waiting for messageq; sleep 2; done;']
      - name: init-cache
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup cache; do echo waiting for cache; sleep 2; done;']
      restartPolicy: Always
