# messageq deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: messageq
    app: aml
    version: {{  .Values.images.tag }}
  name: messageq
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      role: messageq
      app: aml
      version: {{  .Values.images.tag }}
  replicas: {{  .Values.replicas }}
  template:
    metadata:
      labels:
        role: messageq
        app: aml 
        version: {{  .Values.images.tag }}
    spec:
      containers:
      - name: messageq
        image: rabbitmq:3.6.10-management
        ports:
        - name: messageq
          containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_VHOST
          value: /
        - name: RABBITMQ_ERLANG_COOKIE
          value: "1234"
      restartPolicy: Always
