apiVersion: v1
kind: Secret
metadata:
  name: mongo-conn-string
  namespace: {{ .Values.global.namespace }}
data:
  MONGODB_NAME: {{ .Values.databases.mongodb.connection_string | b64enc }}
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace }}
data:
  KEYCLOAK_PASSWORD: {{ .Values.databases.keycloak.db_password | b64enc }}
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: postgresql
  namespace: {{ .Values.global.namespace }}
data:
  POSTGRESQL_PASSWORD: {{ .Values.databases.keycloak.db_password | b64enc }}
type: Opaque

---
apiVersion: v1
data:
  RPI_SHARED_PASS: LkRDQ1NlY3JldDEh
kind: Secret
metadata:
  name: rpi-shared-pwd
  namespace: {{ .Values.global.namespace }}
type: Opaque