# dcc-ui service
apiVersion: v1
kind: Service
metadata:
  name: dcc-ui
  namespace: {{ .Values.global.namespace }}
  labels:
    role: dcc-ui
  annotations:
    nginx.org/websocket-services: "dcc-socketio"
spec:
  ports:
  - port: 8980
    protocol: TCP
  selector:
    role: dcc-ui
---
