# messageq service
apiVersion: v1
kind: Service
metadata:
  name: messageq
  namespace: {{ .Values.application.namespace }}
  labels:
    role: messageq
spec:
  ports:
  - port: 5672
    protocol: TCP
  selector:
    role: messageq
