# Trainer service
apiVersion: v1
kind: Service
metadata:
  name: trainer
  namespace: {{ .Values.global.namespace }}
  labels:
    role: trainer
spec:
  ports:
  - port: 11001
    protocol: TCP
  selector:
    role: trainer
