# ml-servicesapi service
apiVersion: v1
kind: Service
metadata:
  name: ml-servicesapi
  namespace: {{ .Values.global.namespace }}
  labels:
    role: ml-servicesapi
spec:
  ports:
  - name: mlapi
    port: 8910
    targetPort: 8910
  selector:
    role: ml-servicesapi
