# ml-scheduler service
apiVersion: v1
kind: Service
metadata:
  name: ml-scheduler
  namespace: {{ .Values.global.namespace }}
  labels:
    role: ml-scheduler
spec:
  ports:
  - name: mlsched
    port: 8920
    targetPort: 8920
  selector:
    role: ml-scheduler
