---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: {{ include "custom.namespace" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: {{ include "custom.namespace" . }}
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:12
        env:
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-pod-password
              key: POSTGRESQL_PASSWORD
        - name: POSTGRES_DB
          value: keycloak
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /data/postgresql
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ include "custom.namespace" . }}
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql

---
kind: Secret
apiVersion: v1
metadata:
  name: postgresql-pod-password
  namespace: {{ include "custom.namespace" . }}
data:
  POSTGRESQL_PASSWORD: N3JVOHc5bzhvY1RhOFpwMQo=
type: Opaque