# Redis cache service
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: redpoint-mercury
  labels:
    role: cache
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    role: cache
