apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: {{ .Values.global.namespace }}
  labels:
    role: cache
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    role: cache
    
---
{{- if eq .Values.global.deploymentType "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: cache
    app: mercury
    version: {{  .Values.global.image_tag }}
  name: cache
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      role: cache
      app: mercury
      version: {{  .Values.global.image_tag }}
  replicas: {{  .Values.global.replicaCount }}
  template:
    metadata:
      labels:
        role: cache
        app: mercury
        version: {{  .Values.global.image_tag }}
    spec:
      containers:
      - name: cache
        image: redis:3.2.8-alpine
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
{{- end }}

{{- if eq .Values.global.deploymentType "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: cache
    app: mercury
    version: {{  .Values.global.image_tag }}
  name: cache
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      role: cache
      app: mercury
      version: {{  .Values.global.image_tag }}
  replicas: {{  .Values.global.replicaCount }}
  template:
    metadata:
      labels:
        role: cache
        app: mercury
        version: {{  .Values.global.image_tag }}
    spec:
      containers:
      - name: cache
        image: redis:3.2.8-alpine
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
{{- end }}