kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mercury-admin
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  ingressClassName: {{ .Values.global.namespace }}
  tls:
    - secretName: ingress-tls
  rules:
    - host: {{  .Values.ingress.host  }}.{{  .Values.ingress.domain }}
      http:
        paths:
          - path: /admin/api/(.*)
            pathType: Prefix
            backend:
              service:
                name: dcc-servicesapi
                port:
                  number: 8900
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mercury-apis
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/proxy-body-size: 99m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/websocket-services: dcc-socketio
spec:
  ingressClassName: {{ .Values.global.namespace }}
  tls:
    - secretName: ingress-tls
  rules:
    - host: {{  .Values.ingress.host  }}.{{  .Values.ingress.domain }}
      http:
        paths:
          - path: /(api-ml/.*)
            pathType: Prefix
            backend:
              service:
                name: ml-servicesapi
                port:
                  number: 8910
          - path: /(api/.*)
            pathType: Prefix
            backend:
              service:
                name: dcc-servicesapi
                port:
                  number: 8900
          - path: /(socket.io/.*)
            pathType: Prefix
            backend:
              service:
                name: dcc-socketio
                port:
                  number: 8930
          - path: /(auth/.*)
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mercury-docs
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/rewrite-target: /docs/$1
spec:
  ingressClassName: {{ .Values.global.namespace }}
  tls:
    - secretName: ingress-tls
  rules:
    - host: {{  .Values.ingress.host  }}.{{  .Values.ingress.domain }}
      http:
        paths:
          - path: /docs-ml/(.*)
            pathType: Prefix
            backend:
              service:
                name: ml-servicesapi
                port:
                  number: 8910
          - path: /docs/(.*)
            pathType: Prefix
            backend:
              service:
                name: dcc-servicesapi
                port:
                  number: 8900

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mercury-ui
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.global.namespace }}
  tls:
    - secretName: ingress-tls
  rules:
    - host: {{  .Values.ingress.host  }}.{{  .Values.ingress.domain }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: dcc-ui
                port:
                  number: 8080 #8980
          - path: /admin/(.*)
            pathType: Prefix
            backend:
              service:
                name: dcc-admin-ui
                port:
                  number: 8080 #8990

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mercury-ml-docs
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/proxy-body-size: 99m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/websocket-services: dcc-socketio
spec:
  ingressClassName: {{ .Values.global.namespace }}
  tls:
    - secretName: ingress-tls
  rules:
    - host: {{  .Values.ingress.host  }}.{{  .Values.ingress.domain }}
      http:
        paths:
          - path: /api-ml/docs/
            pathType: Prefix
            backend:
              service:
                name: ml-servicesapi
                port:
                  number: 8910
